import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/Navbar";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import MySissionProvider from "./_providers/MySissionProvider";
import CartContextProvider from "./_context/cartContextProvider";
import WishlistContextProvider from "./_context/wishlistContextProvider";



const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fresh cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} antialiased`}
      >
        <MySissionProvider>
          <CartContextProvider>
            <WishlistContextProvider>

              <Toaster
                toastOptions={{
                  classNames: {
                    toast: '!rounded-xl !px-4 !py-3.5 !flex !items-center !gap-3 !shadow-lg',
                    success: '!bg-green-600 !text-white !shadow-green-600/25',
                    error: '!bg-red-600 !text-white !shadow-red-600/25',
                    title: '!text-sm !font-medium',
                    description: '!text-xs !opacity-75',
                    closeButton: '!text-white/70 hover:!text-white',
                  },
                }}
              />
              <Navbar />
              {children}
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MySissionProvider>
      </body>
    </html>
  );
}
