import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/Navbar";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";
import MySissionProvider from "./_providers/MySissionProvider";
import CartContextProvider from "./_context/cartContextProvider";
import WishlistContextProvider from "./_context/wishlistContextProvider";



const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fresh cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} antialiased`}
      >
        <MySissionProvider>
          <CartContextProvider>
            <WishlistContextProvider>

              <Toaster/>
              <Navbar />
              {children}
              <Footer />
            </WishlistContextProvider>
          </CartContextProvider>
        </MySissionProvider>
      </body>
    </html>
  );
}
